"""CheckinResult — the response from Ollama's check-in prompt.

After a journal entry is written, Ollama returns a short empathetic
question and actionable choices for the maker to reflect on.
"""

from dataclasses import dataclass, field


@dataclass
class CheckinResult:
    """A check-in generated by the local LLM.

    Attributes:
        question: A short personal question, max ~12 words.
        choices:  List of actionable/emotional responses (3–5 items).
    """

    question: str
    choices: list[str] = field(default_factory=list)
